export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const SORT_PRODUCT = "SORT_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const DETAILS_PROD = "DETAILS_PROD";
